# Generated by Django 5.1.4 on 2025-03-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb2file', models.FileField(null=True, upload_to='books/', verbose_name='Файл книги')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.book', verbose_name='ID_книги')),
            ],
        ),
    ]
