# Generated by Django 5.1.4 on 2025-03-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netbook',
            old_name='book_id',
            new_name='book',
        ),
    ]
