# Generated by Django 5.1.4 on 2025-03-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_book_id_netbook_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetBook',
        ),
    ]
