# Generated by Django 5.1.4 on 2025-03-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fb2file',
            field=models.FileField(null=True, upload_to='books/', verbose_name='Файл книги'),
        ),
    ]
