# Generated by Django 5.1.4 on 2025-03-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_book_fb2file'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueofbooks',
            name='is_web',
            field=models.BooleanField(default=False, verbose_name='Выдана онлайн'),
        ),
    ]
