# Generated by Django 5.1.4 on 2026-05-15 21:02

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/kasip/Desktop/Library/private_media')), upload_to='books/{book.id}/', verbose_name='Файл книги'),
        ),
    ]
