# Generated by Django 5.1.4 on 2026-05-15 21:13

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_book_epub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/kasip/Desktop/Library/private_media')), upload_to='books/{self.id}/', verbose_name='Файл книги'),
        ),
    ]
