# Generated by Django 5.1.4 on 2025-03-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_issueofbooks_is_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueofbooks',
            name='is_web',
        ),
        migrations.AddField(
            model_name='book',
            name='web_amount',
            field=models.IntegerField(default=0, verbose_name='Количество экземпляров в интернет-библиотеке'),
        ),
        migrations.AddField(
            model_name='issueofbooks',
            name='isweb',
            field=models.BooleanField(default=False, verbose_name='Веб-версия'),
        ),
    ]
