# Generated by Django 5.1.4 on 2025-03-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_remove_issueofbooks_is_web_book_web_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueofbooks',
            old_name='isweb',
            new_name='is_web',
        ),
    ]
