# Generated by Django 5.1.4 on 2025-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_book_fb2file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fb2file',
            field=models.FileField(null=True, upload_to='books/', verbose_name='Файл книги'),
        ),
    ]
