# Generated by Django 5.1.4 on 2025-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_rename_isweb_issueofbooks_is_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=0, upload_to='covers/', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2file',
            field=models.FileField(blank=True, upload_to='books/', verbose_name='Файл книги'),
        ),
    ]
