# Generated by Django 5.1.4 on 2026-05-16 09:42

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_alter_book_epub_alter_bookchapter_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TocBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toc_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/kasip/Desktop/Library/private_media')), upload_to='', verbose_name='Файл оглавления')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engine.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Оглавление книги',
                'verbose_name_plural': 'Оглавления книг',
            },
        ),
    ]
