# Generated by Django 5.1.4 on 2025-03-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_remove_book_cover_url_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
