# Generated by Django 5.1.4 on 2025-03-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_book_cover_alter_book_fb2file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
    ]
