# Generated by Django 5.1.4 on 2026-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_tocbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocbook',
            name='toc_file',
        ),
        migrations.AddField(
            model_name='tocbook',
            name='toc',
            field=models.JSONField(default=list),
        ),
    ]
