# Generated by Django 5.1.4 on 2026-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_remove_tocbook_toc_file_tocbook_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
