# Generated by Django 5.1.4 on 2026-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default_cover', null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
