# Generated by Django 5.1.4 on 2026-05-26 16:43

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/default_cover.png', upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to='', verbose_name='Файл главы'),
        ),
    ]
