# Generated by Django 5.1.4 on 2026-05-26 17:45

import django.core.files.storage
import engine.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='content',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/default_cover.png', upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/kasip/Desktop/Library/private_media')), upload_to=engine.models.chapter_upload_path, verbose_name='Файл главы'),
        ),
    ]
