# Generated by Django 5.1.4 on 2026-05-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_alter_book_cover_alter_book_epub_and_more'),
        ('engine', '0012_remove_bookchapter_content_alter_book_cover_and_more'),
    ]

    operations = [
    ]
