# Generated by Django 5.1.4 on 2026-05-30 14:11

import django.core.files.storage
import django.db.models.deletion
import engine.models
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_alter_book_epub_alter_bookchapter_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/kasip/Desktop/Library/private_media')), upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/kasip/Desktop/Library/private_media')), upload_to=engine.models.chapter_upload_path, verbose_name='Файл главы'),
        ),
        migrations.AlterField(
            model_name='issueofbooks',
            name='reader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
