# Generated by Django 5.1.4 on 2026-05-31 19:00

import django.core.files.storage
import engine.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_alter_book_epub_alter_bookchapter_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to=engine.models.chapter_upload_path, verbose_name='Файл главы'),
        ),
    ]
