# Generated by Django 5.1.4 on 2026-05-31 19:10

import engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_alter_book_epub_alter_bookchapter_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, storage=engine.models.get_private_storage, upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=engine.models.get_private_storage, upload_to=engine.models.chapter_upload_path, verbose_name='Файл главы'),
        ),
    ]
