# Generated by Django 5.1.4 on 2026-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_alter_book_epub_alter_bookchapter_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Автор'),
        ),
    ]
