# Generated by Django 5.1.4 on 2026-06-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueofbooks',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время выдачи'),
        ),
        migrations.AlterField(
            model_name='issueofbooks',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время возврата'),
        ),
    ]
